name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened, closed, reopened, merged]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord      
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"content\": \"🚀 A pull request has been \"}" \
        "https://discord.com/api/webhooks/1279301635713011755/LtFSs-lHgpFRRH6_QEkQYJSe32frUeShcrznNoS_nldqVSeSpqcJVVI8UKY_zZCInZOy"
