Python
name: Notify

on:
  pull_request:
    types: [merged]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Send Discord notification
        uses: actions/http-get@v3
        with:
          url: https://discord.com/api/webhooks/https://discord.com/api/webhooks/1279301635713011755/LtFSs-lHgpFRRH6_QEkQYJSe32frUeShcrznNoS_nldqVSeSpqcJVVI8UKY_zZCInZOy
          data: '{"content": "**Pull Request Merged!**\nRepository: ${{ github.repository }}\nPR: ${{ github.event.pull_request.html_url }}"}'
          headers:
            'Content-Type': application/json
