name: Notify Discord on Pull Request

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        PR_ACTION: ${{ github.event.action }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
        PR_USER: ${{ github.event.pull_request.user.login }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"content\": \"🚀 A pull request has been $PR_ACTION by $PR_USER: **$PR_TITLE**. Check it out here: $PR_URL\"}" \
        $DISCORD_WEBHOOK_URL
        
