name: Notify Discord on Pull Request Merged

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR was merged
      if: github.event.pull_request.merged == true
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"content\": \"✅ A pull request by ${{ github.event.pull_request.user.login }} has been merged: **${{ github.event.pull_request.title }}**. You can review it here: ${{ github.event.pull_request.html_url }}\"}" \
        https://discord.com/api/webhooks/1279301635713011755/LtFSs-lHgpFRRH6_QEkQYJSe32frUeShcrznNoS_nldqVSeSpqcJVVI8UKY_zZCInZOy
